platform :ios, '9.0'

target ‘ShowTicket’
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 4.0.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDCycleScrollView','~> 1.75'
pod 'FMDB', '~> 2.7.2'
pod 'JTCalendar', '~> 2.2.2'
pod 'SDCycleScrollView','~> 1.75'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'YYModel', '~> 1.0.4'
pod 'YTKKeyValueStore'
pod 'WMPageController', '~> 2.3.0'
